import fs from 'node:fs';
import path from 'node:path';
import type { DiffPayload } from './diff.js';
import type { AuditResult } from './llm.js';
import type { SASTFinding } from './sast.js';

export interface AuditRunArtifacts {
  timestamp: string;
  targetBranch: string;
  model: string;
  diffStats: {
    filesChanged: string[];
    lineCount: number;
    isTruncated: boolean;
  };
  sastFindingsCount: number;
  sastFindings: SASTFinding[];
  geminiStatus: 'SUCCESS' | 'SKIPPED_NO_KEY' | 'FAILED_API_ERROR';
  geminiAuditResult: AuditResult;
  passed: boolean;
  failOnThreshold: string;
  logs: string[];
}

export function writeRunArtifacts(
  outputDir: string,
  markdownReport: string,
  artifacts: AuditRunArtifacts,
): void {
  if (!outputDir) return;

  try {
    const resolvedDir = path.resolve(outputDir);
    fs.mkdirSync(resolvedDir, { recursive: true });

    // Ensure output directory is automatically gitignored in any repository
    const gitignorePath = path.join(resolvedDir, '.gitignore');
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(
        gitignorePath,
        `# Auto-generated by keel-sec-guard: Ignore all audit artifacts\n*\n`,
        'utf-8',
      );
    }

    // 1. Write Markdown Report
    const reportPath = path.join(resolvedDir, 'audit-report.md');
    fs.writeFileSync(reportPath, markdownReport, 'utf-8');

    // 2. Write Structured JSON Diagnostics
    const jsonPath = path.join(resolvedDir, 'audit-run.json');
    fs.writeFileSync(jsonPath, JSON.stringify(artifacts, null, 2), 'utf-8');

    // 3. Write Execution Log
    const logPath = path.join(resolvedDir, 'audit.log');
    const logContent = artifacts.logs.join('\n');
    fs.writeFileSync(logPath, logContent, 'utf-8');

    console.log(`📁 Saved audit artifacts to ${resolvedDir}/`);
    console.log(`   ├── .gitignore (auto-created)`);
    console.log(`   ├── audit-report.md`);
    console.log(`   ├── audit-run.json`);
    console.log(`   └── audit.log`);
  } catch (error) {
    console.error(`⚠️ Failed to write audit artifacts to directory ${outputDir}:`, error);
  }
}
